# Generated by Django 3.2.7 on 2021-11-05 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 11, 3, 26, 357476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='ontime',
            field=models.BooleanField(),
        ),
    ]
