# Generated by Django 3.2.4 on 2021-12-24 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
