# Generated by Django 3.2.7 on 2021-10-27 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.TextField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaMurid', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
                ('ontime', models.BooleanField()),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.task')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(to='login.Subject'),
        ),
    ]
