# Generated by Django 3.2.7 on 2021-10-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211027_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subject',
            new_name='subjects',
        ),
    ]
