# Generated by Django 3.2.7 on 2021-11-05 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211105_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='title',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 13, 22, 48, 402867, tzinfo=utc)),
        ),
    ]
