# Generated by Django 3.2.8 on 2021-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211029_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.BooleanField(default=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BooleanField(default=False, verbose_name='password'),
        ),
    ]
