# Generated by Django 3.2.7 on 2021-10-27 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_subject_user_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissions',
            name='NamaMurid',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='Name',
            field=models.CharField(max_length=255),
        ),
    ]
