# Generated by Django 3.2.7 on 2021-11-05 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
