# Generated by Django 3.2.7 on 2021-11-05 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20211105_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='title',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 20, 46, 25, 989706)),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='ontime',
            field=models.BooleanField(default=True),
        ),
    ]
