# Generated by Django 3.2.7 on 2021-11-05 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20211105_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 15, 18, 1, 97193, tzinfo=utc)),
        ),
    ]
