# Generated by Django 3.2.8 on 2021-11-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_task_score'),
        ('login', '0009_alter_submissions_date'),
    ]

    operations = [
    ]
