# Generated by Django 3.2.8 on 2021-11-05 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_merge_0002_task_score_0009_alter_submissions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='nilai',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissions',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissions',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='ontime',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(max_length=300),
        ),
    ]
