# Generated by Django 3.2.7 on 2021-10-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_task_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaMurid', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
                ('ontime', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('allsubjects', models.ManyToManyField(to='TaskManager.Subject')),
                ('submissions', models.ManyToManyField(to='TaskManager.Submissions')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='submissions',
            field=models.ManyToManyField(to='TaskManager.Submissions'),
        ),
    ]
