# Generated by Django 3.2.7 on 2021-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_auto_20211027_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submissions',
        ),
        migrations.DeleteModel(
            name='Murid',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
