# Generated by Django 3.2.9 on 2021-11-03 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=256)),
                ('birth_date', models.DateField(default=datetime.date(2021, 11, 3))),
                ('address', models.CharField(default='Name', max_length=256)),
            ],
        ),
    ]
