# Generated by Django 3.2.4 on 2021-12-24 01:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='undraw_profile.svg', upload_to='profile_pics')),
                ('name', models.CharField(default='Enter Name', max_length=256)),
                ('birth_date', models.DateField(default=datetime.date(2021, 12, 24))),
                ('address', models.CharField(default='Enter Address', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
