<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-11-04 15:37
=======
# Generated by Django 3.2.9 on 2021-11-03 12:12
>>>>>>> 895d920d906c78739bbed892074bd829788cf032

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2021, 11, 4)),
=======
            field=models.DateField(default=datetime.date(2021, 11, 3)),
>>>>>>> 895d920d906c78739bbed892074bd829788cf032
        ),
    ]
