<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-11-05 07:07
=======
# Generated by Django 3.2.7 on 2021-11-04 02:39
>>>>>>> 895d920d906c78739bbed892074bd829788cf032

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('dashboard', '0002_alter_profile_birth_date'),
=======
        ('dashboard', '0002_profile_user'),
>>>>>>> 895d920d906c78739bbed892074bd829788cf032
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2021, 11, 5)),
=======
            field=models.DateField(default=datetime.date(2021, 11, 4)),
>>>>>>> 895d920d906c78739bbed892074bd829788cf032
        ),
    ]
