# Generated by Django 3.2.8 on 2021-10-29 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Name', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 10, 29)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=256),
        ),
    ]
