# Generated by Django 3.2.9 on 2021-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211104_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='undraw_profile.svg', upload_to='profile_pics'),
        ),
    ]
