# Generated by Django 3.2.9 on 2021-11-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_birth_date'),
        ('dashboard', '0004_alter_profile_image'),
    ]

    operations = [
    ]
