# Generated by Django 3.2.9 on 2021-11-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_profile_birth_date'),
        ('dashboard', '0005_merge_20211105_2203'),
    ]

    operations = [
    ]
