# Generated by Django 3.2.8 on 2021-11-05 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_merge_20211105_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Enter Address', max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2021, 11, 6)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Enter Name', max_length=256),
        ),
    ]
