# Generated by Django 3.2.7 on 2021-11-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Name',
            new_name='name',
        ),
    ]
